### ISSUE TITLE
Why does split APK only include debug builds?

### ISSUE THREAD

**Issue by rancidfrog** [mars885/doc-skanner#13]
When splitting up apks is it intended only to include debug builds?
It would be great if normal release builds can be provided.

**Comment by mars885** [comment]
The project does not have release builds and probably never will.

It was a side-project of mine, where I was tinkering with OpenCV for solving a particular real-life problem. It's not production-ready, because it lacks quite a lot of features that most document scanning apps have. However, it may be extremely valuable for others, which is why I open-sourced it.

Hope I asnwered your question.
